"""Prompt construction for the six testing strategies of Huang et al. (2024).

Reference
---------
Y. Huang et al., "Segment anything model for medical images?",
*Medical Image Analysis* 92 (2024) 103061.
Strategy definitions: Sec. 4.1.  Prompt construction rules: Sec. 3.3.
Perturbation protocol: Sec. 4.10 / Table 8.

Why this module exists
----------------------
The authors' repository (``yuhoo0302/Segment-Anything-Model-for-Medical-Images``)
releases only the *box* prompt path (``test_only_box.py``).  The point-prompt
construction of S2-S4 and the jitter protocol of Table 8 exist in the paper as
prose only.  Each rule below therefore carries the sentence it implements, so
that any divergence from the paper is auditable instead of buried in code.

Where the paper is underspecified the choice is marked ``AMBIGUITY``; those
points are collected in the reproducibility section of the report, and the
alternative reading is always reachable through a keyword argument so that the
sensitivity of our results to the reading can be measured rather than assumed.

Conventions
-----------
* Masks are 2-D array-likes, truthy inside the object; shape ``(H, W)``.
* Points and boxes use SAM's convention: ``(x, y)`` = ``(column, row)``.
* Boxes are ``(x_min, y_min, x_max, y_max)`` with **inclusive** maxima, i.e.
  ``x_max`` is the last column that contains object pixels.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

import numpy as np

__all__ = [
    "Prompt",
    "Strategy",
    "STRATEGY_SPEC",
    "bounding_box",
    "center_of_mass",
    "positive_points",
    "negative_points",
    "build_prompt",
    "jitter_prompt",
]

Strategy = Literal["S1", "S2", "S3", "S4", "S5", "S6"]

#: The six testing strategies, verbatim from Sec. 4.1 of the paper.
STRATEGY_SPEC: dict[str, dict] = {
    "S1": {"n_pos": 0, "n_neg": 0, "box": False, "label": "automatic everything mode"},
    "S2": {"n_pos": 1, "n_neg": 0, "box": False, "label": "one positive point"},
    "S3": {"n_pos": 5, "n_neg": 0, "box": False, "label": "five positive points"},
    "S4": {"n_pos": 5, "n_neg": 5, "box": False, "label": "five positive and five negative points"},
    "S5": {"n_pos": 0, "n_neg": 0, "box": True, "label": "one box"},
    "S6": {"n_pos": 1, "n_neg": 0, "box": True, "label": "one box and one positive point"},
}

_SamplingScheme = Literal["centers", "endpoints"]


@dataclass(frozen=True)
class Prompt:
    """A single round of prompts for one object.

    ``point_coords`` is ``(N, 2)`` float32 in ``(x, y)``; ``point_labels`` is
    ``(N,)`` int32 with 1 = positive (foreground) and 0 = negative
    (background), matching SAM's predictor API.  ``box`` is ``(4,)`` float32 or
    ``None``.  For S1 (*everything* mode) all three are ``None``: the grid is
    generated by SAM's own automatic mask generator, not here.
    """

    point_coords: np.ndarray | None
    point_labels: np.ndarray | None
    box: np.ndarray | None
    strategy: Strategy

    @property
    def n_points(self) -> int:
        return 0 if self.point_coords is None else int(self.point_coords.shape[0])


def _as_mask(mask) -> np.ndarray:
    arr = np.asarray(mask)
    if arr.ndim != 2:
        raise ValueError(f"mask must be 2-D, got shape {arr.shape}")
    return arr.astype(bool, copy=False)


def _uniform_subsample(values: np.ndarray, k: int, scheme: _SamplingScheme) -> np.ndarray:
    """Deterministically pick ``k`` entries spread evenly through ``values``.

    Implements "we directly flattened the GT mask to a one-dimensional vector
    and obtained the other positive points by adopting the uniform sampling
    method" (Sec. 3.3, step c).

    AMBIGUITY: "uniform sampling" of k items from m is not unique.  ``centers``
    takes the midpoint of k equal-width bins, which never returns the first or
    last foreground pixel -- those are extreme boundary pixels of the object and
    make poor prompts.  ``endpoints`` (``np.linspace(0, m-1, k)``) does include
    them.  We default to ``centers``; the paper's own figures show interior
    points, which is consistent with this reading.
    """
    m = int(values.size)
    if k <= 0:
        return values[:0]
    if m == 0:
        raise ValueError("cannot sample from an empty index set")
    if scheme == "centers":
        pos = (np.arange(k) + 0.5) * (m / k)
    elif scheme == "endpoints":
        pos = np.linspace(0, m - 1, k) if k > 1 else np.array([(m - 1) / 2.0])
    else:  # pragma: no cover - guarded by typing
        raise ValueError(f"unknown sampling scheme {scheme!r}")
    idx = np.clip(pos.astype(np.int64), 0, m - 1)
    return values[idx]


def _flat_to_xy(flat: np.ndarray, width: int) -> np.ndarray:
    """Convert row-major flat indices into an ``(N, 2)`` array of ``(x, y)``."""
    return np.stack([flat % width, flat // width], axis=1).astype(np.float32)


def center_of_mass(mask) -> tuple[float, float]:
    """Centre of mass of the mask as ``(x, y)`` floats.

    "we first calculated the center of mass of the ground truth (GT) mask"
    (Sec. 3.3, step a).
    """
    m = _as_mask(mask)
    ys, xs = np.nonzero(m)
    if ys.size == 0:
        raise ValueError("mask is empty")
    return float(xs.mean()), float(ys.mean())


def bounding_box(mask) -> np.ndarray:
    """Tight bounding box ``(x_min, y_min, x_max, y_max)``, maxima inclusive.

    "we directly adopted the bounding box of the GT mask without any additional
    operations" (Sec. 3.3).
    """
    m = _as_mask(mask)
    ys, xs = np.nonzero(m)
    if ys.size == 0:
        raise ValueError("mask is empty")
    return np.array([xs.min(), ys.min(), xs.max(), ys.max()], dtype=np.float32)


def positive_points(mask, n: int, *, scheme: _SamplingScheme = "centers") -> np.ndarray:
    """``n`` positive (foreground) points, following Sec. 3.3 steps (a)-(d).

    (b) If the centre of mass falls inside the GT mask it becomes the first
    positive point; (c) the remaining points come from uniform sampling of the
    flattened mask; (d) if the centre of mass falls outside, *all* points come
    from step (c).

    The procedure is fully deterministic -- the paper's stated goal, "to ensure
    randomness, repeatability, and accuracy" of point selection.
    """
    m = _as_mask(mask)
    if n <= 0:
        return np.zeros((0, 2), dtype=np.float32)

    height, width = m.shape
    flat_fg = np.flatnonzero(m.ravel(order="C"))
    if flat_fg.size == 0:
        raise ValueError("mask is empty")

    cx, cy = center_of_mass(m)
    ci, cj = int(round(cy)), int(round(cx))
    com_inside = 0 <= ci < height and 0 <= cj < width and bool(m[ci, cj])

    chunks: list[np.ndarray] = []
    remaining = n
    if com_inside:
        chunks.append(np.array([[cj, ci]], dtype=np.float32))
        remaining -= 1
    if remaining > 0:
        chunks.append(_flat_to_xy(_uniform_subsample(flat_fg, remaining, scheme), width))

    return np.concatenate(chunks, axis=0)[:n]


def negative_points(
    mask,
    n: int,
    *,
    enlarge: float = 2.0,
    scheme: _SamplingScheme = "centers",
) -> np.ndarray:
    """``n`` negative (background) points near, but outside, the object.

    "we aimed to avoid selecting points that were too distant from the target
    region.  Specifically, we first enlarged the bounding box of the GT by two
    times.  The negative points were generated by even sampling in the non-GT
    region" (Sec. 3.3).

    The enlarged box is centred on the tight box, scaled by ``enlarge`` in both
    axes, and clipped to the image; sampling then runs over that window minus
    the object itself.
    """
    m = _as_mask(mask)
    if n <= 0:
        return np.zeros((0, 2), dtype=np.float32)

    height, width = m.shape
    x0, y0, x1, y1 = bounding_box(m)
    cx, cy = (x0 + x1) / 2.0, (y0 + y1) / 2.0
    half_w = (x1 - x0 + 1) * enlarge / 2.0
    half_h = (y1 - y0 + 1) * enlarge / 2.0

    ex0 = max(0, int(np.floor(cx - half_w)))
    ex1 = min(width - 1, int(np.ceil(cx + half_w)))
    ey0 = max(0, int(np.floor(cy - half_h)))
    ey1 = min(height - 1, int(np.ceil(cy + half_h)))

    window = np.zeros_like(m)
    window[ey0 : ey1 + 1, ex0 : ex1 + 1] = True
    background = window & ~m

    flat_bg = np.flatnonzero(background.ravel(order="C"))
    if flat_bg.size == 0:
        raise ValueError(
            "no background pixels inside the enlarged bounding box; "
            "the object fills its neighbourhood entirely"
        )
    return _flat_to_xy(_uniform_subsample(flat_bg, n, scheme), width)


def build_prompt(
    mask,
    strategy: Strategy,
    *,
    scheme: _SamplingScheme = "centers",
    enlarge: float = 2.0,
) -> Prompt:
    """Build the prompt for one object under one of S1-S6."""
    if strategy not in STRATEGY_SPEC:
        raise ValueError(f"unknown strategy {strategy!r}; expected one of {list(STRATEGY_SPEC)}")
    spec = STRATEGY_SPEC[strategy]
    m = _as_mask(mask)

    if strategy == "S1":
        # Everything mode: SAM samples its own m x m grid over the whole image.
        return Prompt(None, None, None, strategy)

    coords: list[np.ndarray] = []
    labels: list[np.ndarray] = []
    if spec["n_pos"]:
        pos = positive_points(m, spec["n_pos"], scheme=scheme)
        coords.append(pos)
        labels.append(np.ones(len(pos), dtype=np.int32))
    if spec["n_neg"]:
        neg = negative_points(m, spec["n_neg"], enlarge=enlarge, scheme=scheme)
        coords.append(neg)
        labels.append(np.zeros(len(neg), dtype=np.int32))

    point_coords = np.concatenate(coords, axis=0) if coords else None
    point_labels = np.concatenate(labels, axis=0) if labels else None
    box = bounding_box(m) if spec["box"] else None
    return Prompt(point_coords, point_labels, box, strategy)


def jitter_prompt(
    prompt: Prompt,
    low: float,
    high: float,
    rng: np.random.Generator,
    *,
    image_shape: tuple[int, int] | None = None,
    box_mode: Literal["perturb", "shift"] = "perturb",
    points: Literal["all", "first"] = "all",
) -> Prompt:
    """Randomly displace a prompt, reproducing the protocol behind Table 8.

    "we added different levels of randomness to the centers and boxes to
    simulate real-life human operation.  Specifically, we enlarge/move the
    boxes/points randomly in 0-10, 10-20, and 20-30 pixels" (Sec. 4.10).

    Points are displaced by a vector of magnitude ``U[low, high]`` in a uniformly
    random direction.

    AMBIGUITY: "enlarge/move" does not say whether a box is translated as a rigid
    rectangle or whether its edges move independently.  ``box_mode="perturb"``
    displaces each of the four coordinates independently (so the box also changes
    size, matching "enlarge"); ``box_mode="shift"`` translates the rectangle
    rigidly.  We default to ``perturb`` and report both, since the paper's
    headline claim -- a 24-30 % DICE drop at the 20-30 px level -- is the single
    number most sensitive to this reading.

    AMBIGUITY: nor does it say how many points move.  The sentence speaks of
    "the centers", and the centre of mass is one point per object, so
    ``points="first"`` displaces only that one and leaves the uniformly sampled
    extras untouched; ``points="all"`` displaces every point.  The choice decides
    an entire conclusion.  Under ``all`` the multi-point strategies are no more
    robust than a single point, because all five points move together; under
    ``first`` four of the five stay put and S3/S4 barely degrade - which is
    exactly the paper's finding that "with the increase in the number of point
    prompts, the decline of DICE could be alleviated".  Running both is how the
    unstated choice is identified rather than guessed.
    """
    if low < 0 or high < low:
        raise ValueError(f"require 0 <= low <= high, got low={low}, high={high}")

    def _offsets(count: int) -> np.ndarray:
        magnitude = rng.uniform(low, high, size=count)
        angle = rng.uniform(0.0, 2.0 * np.pi, size=count)
        return np.stack([magnitude * np.cos(angle), magnitude * np.sin(angle)], axis=1)

    coords = prompt.point_coords
    if coords is not None:
        displacement = np.zeros_like(coords)
        moved = 1 if points == "first" else len(coords)
        displacement[:moved] = _offsets(moved)
        coords = coords + displacement.astype(np.float32)

    box = prompt.box
    if box is not None:
        if box_mode == "shift":
            delta = _offsets(1)[0].astype(np.float32)
            box = box + np.concatenate([delta, delta])
        else:
            magnitude = rng.uniform(low, high, size=4)
            sign = rng.choice([-1.0, 1.0], size=4)
            box = box + (magnitude * sign).astype(np.float32)

    if image_shape is not None:
        height, width = image_shape
        if coords is not None:
            coords = np.stack(
                [np.clip(coords[:, 0], 0, width - 1), np.clip(coords[:, 1], 0, height - 1)],
                axis=1,
            ).astype(np.float32)
        if box is not None:
            box = np.array(
                [
                    np.clip(box[0], 0, width - 1),
                    np.clip(box[1], 0, height - 1),
                    np.clip(box[2], 0, width - 1),
                    np.clip(box[3], 0, height - 1),
                ],
                dtype=np.float32,
            )
            # A perturbation may invert an edge; restore ordering so the box
            # stays well-formed for the predictor.
            box = np.array(
                [
                    min(box[0], box[2]),
                    min(box[1], box[3]),
                    max(box[0], box[2]),
                    max(box[1], box[3]),
                ],
                dtype=np.float32,
            )

    return Prompt(coords, prompt.point_labels, box, prompt.strategy)
